# Generated by Django 2.2 on 2019-05-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpg', models.IntegerField()),
                ('cylinders', models.IntegerField()),
                ('cubicinches', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('weightlbs', models.IntegerField()),
                ('timeto60', models.IntegerField()),
                ('year', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
            ],
        ),
    ]
