# Generated by Django 2.2 on 2019-05-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='cubicinches',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='cylinders',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='hp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='mpg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='timeto60',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='weightlbs',
            field=models.FloatField(),
        ),
    ]
